const { prefix, color } = require('../config.json');

module.exports = {
    name: 'lmgtfy',
    cooldown: 5,
	execute(message, args) {
        var embed
        if (args.length!=0) { embed = {
            "title": "LMGTFY",
            "description": `[Let me google \`${args.join(" ")}\` for you](https://lmgtfy.com/?q=${args.join("+")})\n*Generated by <@${message.author.id}>*`,
            "color": color
        }} else {
            embed = {
                "title": "LMGTFY",
                "description": `You need to say what you want to search for! Usage: \`${prefix}lmgtfy [query]\`\n*Generated by <@${message.author.id}>*`,
                "color": color
            }
        }
        return message.channel.send({embed: embed})
        .catch(error => {
            console.error(`Could not give lmgtfy link to ${message.author.tag}.\n`, error);
            message.reply('There was an error searching for that.');
        });
    },
};