const { prefix, color } = require('../config.json');

module.exports = {
    name: 'search',
    cooldown: 5,
	execute(message, args) {
        var embed
        if (args.length!=0) { embed = {
            "title": "Search Web",
            "description": `[Search Ecosia for \`${args.join(" ")}\`](https://www.ecosia.org/search?q=${args.join("+")})\n\n*Generated by <@${message.author.id}>*`,
            "color": color
        }} else {
            embed = {
                "title": "Search Web",
                "description": `You need to say what you want to search for! Usage: \`${prefix}search [query]\`\n\n*Generated by <@${message.author.id}>*`,
                "color": color
            }
        }
        return message.channel.send({embed: embed})
        .catch(error => {
            console.error(`Could not give search link to ${message.author.tag}.\n`, error);
            message.reply('There was an error searching for that.');
        });
    },
};