const { prefix, color } = require('../config.json');

module.exports = {
    name: 'wiki',
    cooldown: 5,
	execute(message, args) {
        var embed
        if (args.length!=0) response = `https://minecraft.gamepedia.com/index.php?search=${encodeURI(args.join(" "))}`
        else response = `You need to say what you want to search for! Usage: \`${prefix}wiki [query]\`\n*Generated by <@${message.author.id}>*`
        return message.channel.send(response)
        .catch(error => {
            message.reply('There was an error searching for that.');
        });
    },
};